# Generated by Django 3.2.11 on 2022-01-05 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_updated', models.DateTimeField(auto_now=True)),
                ('cat_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=100)),
                ('prd_updated', models.DateTimeField(auto_now=True)),
                ('prd_created', models.DateTimeField(auto_now_add=True)),
                ('prd_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prd_cat_set', to='products.category')),
                ('prd_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
