# Generated by Django 3.2.11 on 2022-01-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prd_discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='prd_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
