# Generated by Django 3.2.11 on 2022-01-07 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20220105_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prd_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prd_cat_set', to='products.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prd_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
